### ISSUE TITLE
Are the arguments to `window.recent` optional?

### ISSUE THREAD

**Issue by phated** [dominictarr/pull-window#3]
@dominictarr I am using https://github.com/pull-stream/pull-level but the `write` examples don't work because it uses `window.recent` internally for which it passes `opts.windowSize` and `opts.windowTime`.  To make the examples work on `pull-level`, the arguments would need to be optional here.  If they aren't optional, the examples on `pull-level` need to be updated (or maybe they can be defaulted in `pull-level`).

I am willing to do either but I need to know where the fix needs to happen.

Thanks!

**Comment by dominictarr** [comment]
Oh, probably it should just be updated to use https://github.com/pull-stream/pull-write
Actually, I havn't found pull-level.write to be that useful, I have more often ended up using pull-write because usually I want to also write some metadata consistent with the batch, (such as a timestamp or sequence number)
